version: 2
jobs:
  build:
    working_directory: ~/stac
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install
          command: |
            sudo apt-get update
            sudo apt-get install curl -y software-properties-common
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g remark-cli remark-validate-links
      - run:
          name: validate
          command: |
            remark -f -u validate-links .
